# Generated by Django 5.2.5 on 2025-08-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('issued_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bin', models.CharField(max_length=12, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('licenses', models.ManyToManyField(blank=True, to='orgs.license')),
            ],
        ),
    ]
