# Generated by Django 5.2.5 on 2025-08-30 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialorg',
            name='bin',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='BIN must be exactly 12 digits', regex='^\\d{12}$')]),
        ),
    ]
